import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from '@/components/side-nav';
import MaxWidthWrapper from '@/components/max-width-wrapper';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      {/* <MaxWidthWrapper> */}
        <div className="flex">
          <SideNav />
          <main className="flex-1">{children}</main>
        </div>
      {/* </MaxWidthWrapper> */}
      {/* <BottomNav /> */}
    </body>
  </html>
  );
}
